### ISSUE TITLE
TypeError: Cannot set property  of undefined

### ISSUE THREAD

**Issue by davidjbradshaw** [markalfred/eslint-plugin-no-constructor-bind#1]
This plugin is crashing with the following error
```
TypeError: Cannot set property 'render' of undefined
    at logMethodDefinition (C:\dev\workspace\channel-theming\node_modules\eslint-plugin-no-constructor-bind\lib\rules\no-constructor-bind.js:122:47)
    at listeners.(anonymous function).forEach.listener (C:\dev\workspace\channel-theming\node_modules\eslint\lib\util\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (C:\dev\workspace\channel-theming\node_modules\eslint\lib\util\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\dev\workspace\channel-theming\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (C:\dev\workspace\channel-theming\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (C:\dev\workspace\channel-theming\node_modules\eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (C:\dev\workspace\channel-theming\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:632:23)
    at nodeQueue.forEach.traversalInfo (C:\dev\workspace\channel-theming\node_modules\eslint\lib\linter.js:750:28)
    at Array.forEach (<anonymous>)
```
It's a large code base and I'm no idea how to track down the code that triggers this. However, I logged out all the data from the line that crashes.

### thisClass
```
{}
```

### node
```
Node {
  type: 'MethodDefinition',
  start: 557,
  end: 1854,
  loc:
   SourceLocation {
     start: Position { line: 17, column: 4 },
     end: Position { line: 56, column: 5 } },
  range: [ 557, 1854 ],
  static: false,
  key:
   Node {
     type: 'Identifier',
     start: 557,
     end: 563,
     loc: SourceLocation { start: [Object], end: [Object], identifierName: 'render' },
     range: [ 557, 563 ],
     name: 'render',
     _babelType: 'Identifier',
     parent: [Circular] },
  computed: false,
  kind: 'method',
  value:
   Node {
     type: 'FunctionExpression',
     start: 563,
     end: 1854,
     loc: SourceLocation { start: [Object], end: [Object] },
     range: [ 563, 1854 ],
     id: null,
     generator: false,
     async: false,
     expression: false,
     params: [],
     body:
      Node {
        type: 'BlockStatement',
        start: 566,
        end: 1854,
        loc: [Object],
        range: [Array],
        body: [Array],
        _babelType: 'BlockStatement',
        parent: [Circular] },
     _babelType: 'FunctionExpression',
     parent: [Circular] },
  _babelType: 'MethodDefinition',
  parent:
   Node {
     type: 'ClassBody',
     start: 287,
     end: 1859,
     loc: SourceLocation { start: [Object], end: [Object] },
     range: [ 287, 1859 ],
     body: [ [Object], [Circular] ],
     _babelType: 'ClassBody',
     parent:
      Node {
        type: 'ClassExpression',
        start: 236,
        end: 1859,
        loc: [Object],
        range: [Array],
        id: [Object],
        superClass: [Object],
        body: [Circular],
        leadingComments: [Array],
        _babelType: 'ClassExpression',
        parent: [Object] } } }
```

Having looked at the code, my guess is that `logMethodDefinition` is being called before `init`.

**Comment by davidjbradshaw** [comment]
I can stop it crashing with the following fix, but not sure if this is the best solution
```
function logMethodDefinition(node) {
  if (!('classMethods' in thisClass)) thisClass.classMethods = {}
  thisClass.classMethods[node.key.name] = node
}
```

**Comment by markalfred** [comment]
@davidjbradshaw thanks for this report. You're 100% right that it's trying to assign before `init` is called.

Typically, a method is defined inside of a `ClassDeclaration`, but I hadn't considered that a `ClassExpression` can also be used to create a class and its methods. From what you logged out, it looks like the grandparent of this method is a `ClassExpression`. So thank you for all the legwork you did here, I'll have a fix shortly.

If you're looking for the code in your codebase that's causing this crash, it will be a component that looks like this:

```js
// ClassExpression
MyComponent = class extends React.Component {
  render() {}
}
```

Rather than this:

```js
// ClassDeclaration
class MyComponent extends React.Component {
  render() {}
}
```

**Comment by davidjbradshaw** [comment]
Thanks for fixing this. I tracked it down to a HoC that was basically doing
```
const HoC = foo => WrappedComponent =>
  return class extends React.Componet {
    render() {
       return <WrappedComponet {...foo} />
    } 
  }
```

**Comment by markalfred** [comment]
Makes sense, thanks for tracking that down @davidjbradshaw 🙇
